import { CheckCircle2, Clipboard, Info, Network, ShieldCheck } from "lucide-react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";

import { importLanObservation, verifyLanBootstrap } from "../lib/api";
import { useI18n } from "../lib/i18n";
import { safeArray, safeDate } from "../lib/safe";
import type { LanBootstrapStatus } from "../types";

export function LanBootstrapPanel(): JSX.Element {
  const { t } = useI18n();
  const queryClient = useQueryClient();
  const [cidr, setCidr] = useState("192.168.50.1/24");
  const [gateway, setGateway] = useState("192.168.50.1");
  const [result, setResult] = useState<LanBootstrapStatus | null>(null);
  const verify = useMutation({ mutationFn: () => verifyLanBootstrap({ cidr, gateway_hint: gateway }), onSuccess: setResult });
  const refresh = async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ["lan-assets"] }), queryClient.invalidateQueries({ queryKey: ["monitoring-startup"] })]); setResult(await verifyLanBootstrap({ cidr, gateway_hint: gateway })); };

  return <section className="min-w-0 rounded-lg border border-raven-border bg-raven-panel/85 p-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 font-semibold"><Network className="h-4 w-4 text-raven-cyan" />{t("Authorized LAN Bootstrap")}</h2><p className="mt-1 max-w-3xl text-sm text-raven-muted">{t("Validate and prepare one approved private network without starting discovery or service checks.")}</p><p className="mt-1 text-xs text-raven-muted">{t("Agent commands retain the <ENROLLMENT_TOKEN> placeholder; secrets are never stored here.")}</p></div><span className="rounded-full border border-cyan-300/30 px-2 py-1 text-xs text-cyan-100">{t("Private local verification only")}</span></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><label className="text-xs text-raven-muted">{t("LAN CIDR input")}<input value={cidr} onChange={(event) => setCidr(event.target.value)} maxLength={43} className="mt-1 w-full rounded border border-raven-border bg-raven-bg px-3 py-2 text-sm text-raven-text" /></label><label className="text-xs text-raven-muted">{t("Gateway hint")}<input value={gateway} onChange={(event) => setGateway(event.target.value)} maxLength={45} className="mt-1 w-full rounded border border-raven-border bg-raven-bg px-3 py-2 text-sm text-raven-text" /></label><button type="button" disabled={verify.isPending} onClick={() => verify.mutate()} className="self-end rounded bg-raven-violet px-3 py-2 text-sm text-white disabled:opacity-50"><ShieldCheck className="mr-1 inline h-4 w-4" />{verify.isPending ? t("Verifying") : t("Verify LAN setup")}</button></div>
    {verify.isError ? <p role="alert" className="mt-3 rounded border border-rose-400/30 bg-rose-500/10 p-3 text-sm text-rose-100">{verify.error instanceof Error ? verify.error.message : t("LAN setup validation failed.")}</p> : null}
    {result ? <BootstrapResult data={result} t={t} /> : <p className="mt-3 text-sm text-raven-muted">{t("192.168.50.1/24 will normalize to the authorized network 192.168.50.0/24 while preserving 192.168.50.1 as the gateway hint.")}</p>}
    {result ? <StaticObservationForm data={result} refreshed={refresh} t={t} /> : null}
  </section>;
}

function BootstrapResult({ data, t }: { data: LanBootstrapStatus; t: (value: string) => string }): JSX.Element {
  const states = [["Backend", data.backend_reachable], ["Migrations", data.migrations_ready], ["Configured CIDR", data.configured_cidr_matches], ["LAN monitoring", data.lan_monitoring_enabled], ["Service checks", data.service_check_enabled], ["Enrollment", data.enrollment_capability_ready], ["Observation path", data.observation_path_available], ["Endpoint telemetry", data.fresh_agents > 0]] as const;
  return <div className="mt-4 min-w-0 space-y-4"><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{states.map(([label, ready]) => <div key={label} className="rounded border border-raven-border bg-raven-panelSoft p-3 text-xs"><span className={ready ? "text-emerald-200" : "text-cyan-100"}>{ready ? <CheckCircle2 className="mr-1 inline h-3.5 w-3.5" /> : <Info className="mr-1 inline h-3.5 w-3.5" />}{t(label)}</span><p className="mt-1 text-raven-muted">{ready ? t("Ready") : t("Needs action")}</p></div>)}</div><div className="rounded border border-raven-border p-3 text-sm"><p><strong>{t("LAN CIDR")}:</strong> <code>{data.normalized_cidr}</code></p><p><strong>{t("Gateway hint")}:</strong> <code>{data.gateway_hint}</code></p><p><strong>{t("Release")}:</strong> {data.release_version}</p><p><strong>{t("Last verification")}:</strong> {safeDate(data.verified_at)?.toLocaleString()}</p><p className="mt-2 text-raven-cyan"><strong>{t("Next action")}:</strong> {t(data.next_action)}</p></div><CopyBlock title={t("Copyable .env guidance")} lines={data.env_lines} /><CopyBlock title={t("Windows endpoint agent")} lines={[data.windows_agent_command]} /><CopyBlock title={t("Linux endpoint agent")} lines={[data.linux_agent_command]} /><ol className="grid gap-2 text-sm sm:grid-cols-2">{safeArray(data.steps).map((step, index) => <li key={step} className="rounded border border-raven-border p-3"><span className="mr-2 text-raven-cyan">{index + 1}.</span>{t(step)}</li>)}</ol><p className="text-xs text-raven-muted">{t("Verification never ran discovery or service checks.")} {data.assets_total} {t("assets")}, {data.fresh_agents}/{data.agents_total} {t("fresh agents")}, {data.assessed_posture} {t("posture assessments")}, {data.open_recommendations} {t("open recommendations")}.</p></div>;
}

function StaticObservationForm({ data, refreshed, t }: { data: LanBootstrapStatus; refreshed: () => Promise<void>; t: (value: string) => string }): JSX.Element {
  const [hostname, setHostname] = useState(""); const [ip, setIp] = useState(""); const [mac, setMac] = useState(""); const [interfaceName, setInterfaceName] = useState(""); const [connectionType, setConnectionType] = useState(""); const [notes, setNotes] = useState(""); const [authorized, setAuthorized] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const mutation = useMutation({ mutationFn: () => importLanObservation({ cidr: data.normalized_cidr, observations: [{ hostname: hostname || undefined, ip_address: ip, mac_address: mac || undefined, interface_name: interfaceName || undefined, connection_type: connectionType || undefined, notes: notes || undefined, is_authorized: authorized, source: "router" }] }), onSuccess: async (value) => { setMessage(value.message); setHostname(""); setIp(""); setMac(""); setNotes(""); await refreshed(); }, onError: (error) => setMessage(error instanceof Error ? error.message : t("Observation import failed.")) });
  return <div className="mt-5 rounded border border-raven-border p-4"><h3 className="font-medium">{t("Manual router observation")}</h3><p className="mt-1 text-xs text-raven-muted">{t("Enter only a device already observed in an authorized router UI. RavenTech does not connect to or scrape the router.")}</p><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><input value={hostname} onChange={(e) => setHostname(e.target.value)} placeholder={t("Hostname or name")} maxLength={255} className="rounded border border-raven-border bg-raven-bg px-3 py-2 text-sm" /><input value={ip} onChange={(e) => setIp(e.target.value)} placeholder="192.168.50.x" maxLength={45} className="rounded border border-raven-border bg-raven-bg px-3 py-2 text-sm" /><input value={mac} onChange={(e) => setMac(e.target.value)} placeholder={t("MAC optional")} maxLength={17} className="rounded border border-raven-border bg-raven-bg px-3 py-2 text-sm" /><input value={interfaceName} onChange={(e) => setInterfaceName(e.target.value)} placeholder={t("Interface optional")} maxLength={100} className="rounded border border-raven-border bg-raven-bg px-3 py-2 text-sm" /><input value={connectionType} onChange={(e) => setConnectionType(e.target.value)} placeholder={t("Connection type optional")} maxLength={100} className="rounded border border-raven-border bg-raven-bg px-3 py-2 text-sm" /><input value={notes} onChange={(e) => setNotes(e.target.value)} placeholder={t("Notes optional")} maxLength={1000} className="rounded border border-raven-border bg-raven-bg px-3 py-2 text-sm xl:col-span-2" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={authorized} onChange={(e) => setAuthorized(e.target.checked)} />{t("Authorized for monitoring")}</label></div><button type="button" onClick={() => mutation.mutate()} disabled={!data.lan_monitoring_enabled || !ip || mutation.isPending} className="mt-3 rounded border border-raven-border px-3 py-2 text-sm disabled:opacity-50">{t("Import observation")}</button>{!data.lan_monitoring_enabled ? <p className="mt-2 text-xs text-cyan-100">{t("Enable LAN monitoring and restart before importing observations.")}</p> : null}{message ? <p className="mt-2 text-xs text-raven-muted">{message}</p> : null}</div>;
}

function CopyBlock({ title, lines }: { title: string; lines: string[] }): JSX.Element { const value = lines.join("\n"); return <div className="min-w-0 rounded border border-raven-border p-3"><div className="flex items-center justify-between gap-2"><h3 className="text-sm font-medium">{title}</h3><button type="button" onClick={() => void navigator.clipboard.writeText(value)} className="rounded border border-raven-border p-2" aria-label={`Copy ${title}`}><Clipboard className="h-4 w-4" /></button></div><pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap break-all rounded bg-raven-bg p-3 text-xs">{value}</pre></div>; }
