from __future__ import annotations

import uuid

from app.models.finding_evidence import FindingEvidence
from app.models.recon_entity import ReconEntity
from app.models.recon_relationship import ReconRelationship
from app.services.intelligence.findings_engine import build_finding_candidates


def test_findings_engine_enriches_sensitive_service_with_defensive_context() -> None:
    investigation_id = uuid.uuid4()
    service = ReconEntity(
        id=uuid.uuid4(),
        investigation_id=investigation_id,
        entity_type="Service",
        value="tcp/3389 rdp",
        properties={"port": "3389", "service": "rdp"},
        source="http",
    )

    findings = build_finding_candidates(
        enrichments=[],
        threat_findings=[],
        entities=[service],
    )

    assert len(findings) == 1
    finding = findings[0]
    assert finding.title == "Sensitive service observed: tcp/3389 rdp"
    assert finding.severity == "high"
    assert "tcp/3389 rdp" in finding.affected_targets
    assert any("3389" in target for target in finding.affected_targets)
    assert finding.remediation_guidance
    assert finding.analyst_notes[0].startswith("Generated by deterministic rule")
    assert finding.framework_mappings
    assert finding.references


def test_findings_engine_builds_relationship_backed_service_finding() -> None:
    investigation_id = uuid.uuid4()
    host = ReconEntity(
        id=uuid.uuid4(),
        investigation_id=investigation_id,
        entity_type="Domain",
        value="vpn.example.com",
        properties={},
        source="dns",
    )
    service = ReconEntity(
        id=uuid.uuid4(),
        investigation_id=investigation_id,
        entity_type="Service",
        value="ssh 22",
        properties={"port": "22", "service": "ssh"},
        source="http",
    )
    relationship = ReconRelationship(
        investigation_id=investigation_id,
        source_entity_id=host.id,
        target_entity_id=service.id,
        relationship_type="HOSTS",
        source="recon",
        properties={},
    )

    findings = build_finding_candidates(
        enrichments=[],
        threat_findings=[],
        entities=[host, service],
        relationships=[relationship],
    )

    titles = {finding.title for finding in findings}
    assert "vpn.example.com hosts sensitive service ssh 22" in titles


def test_findings_engine_uses_stored_evidence_for_recurring_patterns() -> None:
    entity_id = uuid.uuid4()
    evidence = [
        FindingEvidence(
            finding_id=uuid.uuid4(),
            recon_entity_id=entity_id,
            evidence_type="http_header",
            source="http",
            description=f"Header evidence {index}",
            data={"target": f"app-{index}.example.com"},
        )
        for index in range(3)
    ]
    entity = ReconEntity(
        id=entity_id,
        investigation_id=uuid.uuid4(),
        entity_type="Domain",
        value="example.com",
        properties={},
        source="dns",
    )

    findings = build_finding_candidates(
        enrichments=[],
        threat_findings=[],
        entities=[entity],
        stored_evidence=evidence,
    )

    assert findings[0].title == "Recurring evidence pattern: http_header"
    assert findings[0].source == "stored-evidence"
    assert findings[0].affected_targets == [
        "example.com",
        "app-0.example.com",
        "app-1.example.com",
        "app-2.example.com",
    ]
